module Decentworks
  module DateSupport
    def self.configure: () ?{ (::Decentworks::DateSupport::Configuration) -> void } -> void
    def self.configuration: -> ::Decentworks::DateSupport::Configuration

    def self.reset_configuration!: -> nil

    def self.first_quarter_month_name: -> Symbol
    def self.first_quarter_month: -> Integer
    def self.first_quarter_month_offset: -> Integer

    class Configuration
      MONTHS: Hash[Symbol, Integer]
      DEFAULT: Symbol

      attr_reader first_quarter_month_name: Symbol

      def first_quarter_month_name=: (Symbol) -> void

      def first_quarter_month: -> Integer

      def first_quarter_month_offset: -> Integer
    end
  end
end
